### ISSUE TITLE
avalon.textbox组件问题

### ISSUE THREAD

**Issue by liminghui** [RubyLouvre/avalon.oniui#712]
avalon.textbox.html页面
第6行 <code>ms-visible="textboxToggle"</code>
avalon.textbox.js里面不存在<code>textboxToggle</code>变量

在avalon 1.4.6.1会出现如下警告(请无视<code>http://localhost:27483/</code>)
<code>warning:exception throwed in [avalon.injectBinding]  ReferenceError: textboxToggle is not defined
    at Number.eval (eval at parseExpr (http://localhost:27483/Content/js/avalon/avalon.js:2881:23), <anonymous>:5:8)
    at Function.avalon.injectBinding (http://localhost:27483/Content/js/avalon/avalon.js:1826:68)
    at parseExprProxy (http://localhost:27483/Content/js/avalon/avalon.js:2913:16)
    at Object.bindingHandlers.visible (http://localhost:27483/Content/js/avalon/avalon.js:4589:5)
    at executeBindings (http://localhost:27483/Content/js/avalon/avalon.js:2963:35)
    at scanAttr (http://localhost:27483/Content/js/avalon/avalon.js:3099:13)
    at scanTag (http://localhost:27483/Content/js/avalon/avalon.js:3207:5)
    at Function.avalon.scan (http://localhost:27483/Content/js/avalon/avalon.js:2924:5)
    at Object.avalon.ui.textbox.avalon.define.vm.$init (http://localhost:27483/Content/js/avalon/oniui/textbox/avalon.textbox.js:126:24)
    at Object.bindingHandlers.widget (http://localhost:27483/Content/js/avalon/avalon.js:4641:24)</code>

**Comment by roscoe054** [comment]
这只是调试信息，运行其实是没有错误的。可以用avalon.config({debug: false})关闭调试信息。
